# Generated by Django 3.1.5 on 2021-07-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210711_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='default_avatar',
        ),
    ]
